### PR TITLE
Emit a closing balance based on meta information ("Saldo") for credit card ("Kreditkarte")

### PR DESCRIPTION
**Pull request by dmerkert**
Closely oriented on pull request #4

### CODE REVIEW

**Comment by siddhantgoel** [comment]
Thanks for the PR! Could you please fix the `flake8` errors too? Otherwise the changes look good to merge.

**Comment by siddhantgoel** [comment]
I'll try to push a new release this weekend! :snail:

**Comment by siddhantgoel** [comment]
@dmerkert I just pushed `v0.6.0` which includes these changes and the bugfix you pushed in #8 .

**Comment by dmerkert** [comment]
Dear Siddhant,

thank you for the great work and for the quick release.


With best regards, 

Dennis

Am 11. August 2018 13:53:39 MESZ schrieb Siddhant Goel <notifications@github.com>:
>@dmerkert I just pushed `v0.6.0` which includes these changes and the
>bugfix you pushed in #8 .
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/siddhantgoel/beancount-dkb/pull/7#issuecomment-412270414

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Pull request merged**
